# Generated by Django 4.0.8 on 2023-01-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_employee_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_doc',
            name='adhar_card_file',
            field=models.ImageField(blank=True, null=True, upload_to='adhar_card_file'),
        ),
    ]
