# Generated by Django 4.0.8 on 2023-01-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_alter_employee_doc_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_doc',
        ),
    ]
