# Generated by Django 4.1.5 on 2023-02-02 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enroll', '0010_passpost_pan_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passpost',
            new_name='Passport',
        ),
    ]
